Shell linter
thesecuresoftwarefactory/ssf pull request #124
Opened 2022-01-25 04:07 UTC by anniepamela2020

Edit and lint shell files using shellcheck

Fixes the syntax in the shell scripts

2022-01-25 17:51 UTC, bradbeck commented on Makefile
> +	shellcheck "**/*.sh" "#docs" "#platform" "#scripts"
```suggestion
	shellcheck "**/*.sh" "#docs" "#platform" "#scripts"

```

2022-01-25 17:51 UTC, bradbeck commented on platform/00-kubernetes-minikube-setup.sh
> +"HELM_SHA256=6cd6cad4b97e10c33c978ff3ac97bb42b68f79766f1d2284cfd62ec04cd177f4"
```suggestion
HELM_SHA256="6cd6cad4b97e10c33c978ff3ac97bb42b68f79766f1d2284cfd62ec04cd177f4"
```

2022-01-25 17:53 UTC, bradbeck commented on docs/bootstrap.sh
> +# C_YELLOW='\033[33m'
```suggestion
```

2022-01-25 17:53 UTC, bradbeck commented on platform/10-tekton-setup.sh
> +#C_RED='\033[31m'
```suggestion
```

2022-01-25 17:53 UTC, bradbeck commented on platform/20-spire-setup.sh
> +#C_GREEN='\033[32m'
```suggestion
```

2022-01-25 17:53 UTC, bradbeck commented on platform/20-spire-setup.sh
> +#C_RED='\033[31m'
```suggestion
```

2022-01-25 17:57 UTC, bradbeck commented on scripts/provenance.sh
> +  "$TASKRUN_JSON "> signature.pub
```suggestion
  "$TASKRUN_JSON" > signature.pub
```

2022-01-25 18:12 UTC, bradbeck commented on platform/20-spire-setup.sh
> +  if [ $# -lt 2 ] || [ $# -lt "$1" ] || [ $# != "-spiffeID" ]; then
```suggestion
  if [ $# -lt 2 ] || [ "$1" != "-spiffeID" ]; then
```

2022-01-25 18:16 UTC, bradbeck commented on scripts/gen-keys.sh
> +: "${COSIGN_PASSWORD:=""}"
```suggestion
: "${COSIGN_PASSWORD:=}"
```

2022-01-25 18:53 UTC, bradbeck commented on Makefile
> +	shellcheck "**/*.sh" "#docs" "#platform" "#scripts"
This syntax doesn't appear to work for me.

2022-01-25 19:40 UTC, rgreinho requested changes
Good job overall 👍 

Just a few minor comments to address.

2022-01-25 19:40 UTC, rgreinho commented on Makefile
> +shell-linter: ## Lint shell files
Should be "lint-shell" to be consistent with the other tasks.

2022-01-25 19:40 UTC, rgreinho commented on docs/bootstrap.sh
> +# C_YELLOW='\033[33m'
Remove it if it is not being used.

2022-01-25 19:40 UTC, rgreinho commented on platform/10-tekton-setup.sh
> +#C_RED='\033[31m'
Remove it if it is not being used.

2022-01-25 19:40 UTC, rgreinho commented on platform/20-spire-setup.sh
> +#C_RED='\033[31m'
Remove them if they are not being used.

2022-01-25 19:40 UTC, rgreinho commented on Makefile
> +	shellcheck "**/*.sh" "#docs" "#platform" "#scripts"
Adding a meta-task calling all the lint tasks would be great.

2022-01-26 15:03 UTC, bradbeck commented on Makefile
> +	shfmt -f ./ | xargs shellcheck
```suggestion
	shfmt -f ./ | xargs shellcheck

```

2022-01-26 15:04 UTC, bradbeck commented on scripts/provenance.sh
> +  "$TASKRUN_JSON"> signature.pub
```suggestion
  "$TASKRUN_JSON" > signature.pub
```

2022-01-26 21:40 UTC, bradbeck submitted a review, later dismissed

2022-01-31 19:06 UTC, bradbeck commented on Makefile
> +  Task: linter-markdown lint-yaml lint-shell
```suggestion
.PHONY: linter
linter:  linter-markdown lint-yaml lint-shell ## Run all linters

```

2022-02-01 16:55 UTC, bradbeck approved these changes

2022-02-02 18:02 UTC, trmiller commented
> Good job overall 👍
> 
> Just a few minor comments to address.

@rgreinho - are these addressed from your POV quite yet?

2022-02-03 14:10 UTC, rgreinho approved these changes

2022-02-03 14:10 UTC, merged